# Generated by Django 3.0 on 2020-05-02 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='supervisors', to='project.Groups')),
                ('supervisor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_group', to='project.Department')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_group', to='project.Groups')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hod', to='project.Department')),
                ('hod_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hod', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinalProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('data_science', 'data_science'), ('project_proposal', 'Project Proposal'), ('project_erd', 'Project (ERD)'), ('time_management', 'Time Management')], default='data_science', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('introduction', models.TextField(default=False)),
                ('content', models.TextField()),
                ('problem_statement', models.TextField(default=False)),
                ('scope', models.TextField(default=False)),
                ('keywords', models.CharField(max_length=300)),
                ('technology', models.CharField(max_length=300)),
                ('source_code', models.CharField(default=False, max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.School')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='Dean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dean_name', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='dean', to=settings.AUTH_USER_MODEL)),
                ('school_id', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='dean', to='project.School')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='coordinator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
