# Generated by Django 3.0 on 2020-05-02 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('group_email', models.CharField(max_length=250)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='project.Department')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=2500)),
                ('school_location', models.CharField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=500)),
                ('project_description', models.TextField(max_length=10000)),
                ('group_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='project.Groups')),
            ],
        ),
        migrations.CreateModel(
            name='GroupProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files_type', models.CharField(choices=[('project_title', 'Project Title'), ('project_proposal', 'Project Proposal'), ('project_erd', 'Project (ERD)'), ('time_management', 'Time Management'), ('project_scope', 'Project scope'), ('project_cost', 'Project Cost'), ('project_backend', 'Project Backend'), ('project_frontend', 'Project Frontend'), ('project_test', 'Project Test'), ('deployment', 'Deployment'), ('project_book', 'Project Book')], default='project_title', max_length=100)),
                ('file_title', models.CharField(max_length=200)),
                ('file_description', models.FileField(upload_to='project_file')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_progress', to='project.Groups')),
            ],
        ),
        migrations.CreateModel(
            name='FinalProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('data_science', 'data_science'), ('project_proposal', 'Project Proposal'), ('project_erd', 'Project (ERD)'), ('time_management', 'Time Management')], default='data_science', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('introduction', models.TextField(default=False)),
                ('content', models.TextField()),
                ('problem_statement', models.TextField(default=False)),
                ('scope', models.TextField(default=False)),
                ('source_code', models.CharField(default=False, max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='school_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='project.School'),
        ),
    ]
