# Generated by Django 3.0 on 2020-05-07 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20200506_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprogress',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='groupprogress',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupprogress',
            name='status',
            field=models.CharField(default='Pending ...', max_length=120),
        ),
    ]
