# Generated by Django 3.0.7 on 2021-01-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_annoucements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprogress',
            name='files_type',
            field=models.CharField(choices=[('project_title', 'Project Title'), ('project_proposal', 'Project Proposal'), ('project_erd', 'Project (ERD)'), ('chapter I', 'chapter I'), ('chapter II', 'chapter II'), ('chapter III', 'chapter III')], default='project_title', max_length=100),
        ),
    ]
